### ISSUE TITLE
Get travis working

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/SciPyDiffEq.jl#2]
@tkf can you help me find out how to get Travis to install SciPy for this?

**Comment by tkf** [comment]
Sorry, I probably can't touch this for ~two weeks.

**Comment by ChrisRackauckas** [comment]
No worries: no rush on this.

**Comment by ChrisRackauckas** [comment]
@stevengj are you familiar with why `pyimport_conda` won't work on Travis? Everything seems to work smoothly locally, but I can't figure out why Travis seems to specifically have an issue.

https://github.com/JuliaDiffEq/SciPyDiffEq.jl/blob/master/src/SciPyDiffEq.jl#L18

**Comment by tkf** [comment]
(Oops I forgot about this issue)

I think you just need to set `PYTHON` in the CI. I'm trying it in #5.
